<?php
/**
 * Created by PhpStorm.
 * User: takahiro
 * Date: 2017/02/14
 * Time: 22:36
 */
require_once 'business_person.php';

class HetareBusinessPerson extends BusinessPerson
{
    public function work()
    {
        parent::work(); // TODO: Change the autogenerated stub
        print 'ぼちぼち'.PHP_EOL;
    }
}